### ISSUE TITLE
Change the default scan directory for the Ubuntu package

### ISSUE THREAD

**Issue by GnomoP** [bb010g/betterdiscordctl#10]
When installed through the .deb package, which most Ubuntu and Ubuntu derivatives users do, Discord is installed in /usr/share, instead of in /opt like in the Arch package. Changing the default scan directory for the package distributed at the ppa would be a nice tweak to have out-of-the-box, though it isn't anything mind-bogging. Great script, btw

**Comment by ObserverOfTime** [comment]
I could change the scan directory for the PPA, but is it a good idea for the script on the PPA to behave differently than the one here?

**Comment by ObserverOfTime** [comment]
I thought of a way to avoid having differences between the packages.
Debian and its derivatives, including Ubuntu and its own derivatives, have `/etc/debian_version` and/or `/etc/debian_release`. We could check whether they exist and change the scan location to `/usr/share` if they do.

**Comment by ObserverOfTime** [comment]
@bb010g Should we implement this? What do you think?

**Comment by piks** [comment]
This issue was closed, and it seems some code was added to attempt this but mine still doesn't detect my installation

> pika@pika-mint /usr/local/bin $ betterdiscordctl -f PTB
ERROR: Discord installation not found.
pika@pika-mint /usr/local/bin $ betterdiscordctl -s /usr/share -f PTB
Discord: /usr/share/discord-ptb
Modules: /home/pika/.config/discordptb/0.0.13/modules
Core patched: yes
Index modified: yes
Linked core directory: /home/pika/.local/share/betterdiscordctl/bd/0
Linked core repository: https://github.com/rauenzi/BetterDiscordApp
pika@pika-mint /usr/local/bin $ betterdiscordctl -V
betterdiscordctl 1.5.0
pika@pika-mint /usr/local/bin $

**Comment by ObserverOfTime** [comment]
Right, looks like it doesn't work properly after all...

**Comment by ObserverOfTime** [comment]
@piks Please try the latest master.

**Comment by piks** [comment]
`pika@pika-mint ~/bot/nodev3 $ betterdiscordctl --version
betterdiscordctl 1.6.0

pika@pika-mint ~/bot/nodev3 $ betterdiscordctl status
ERROR: Discord installation not found.

pika@pika-mint ~/bot/nodev3 $ betterdiscordctl status -f PTB
ERROR: Discord installation not found.

pika@pika-mint ~/bot/nodev3 $ betterdiscordctl status -f PTB -s /usr/share
Discord: /usr/share/discord-ptb
Modules: /home/pika/.config/discordptb/0.0.15/modules
Index modified: no
Linked injector directory: no
Linked injector repository: no
`

**Comment by ObserverOfTime** [comment]
Well, we'll fix it eventually.
