### ISSUE TITLE
Config Directory Not Found/ Directory Not Found in.

### ISSUE THREAD

**Issue by LelloTech** [bb010g/betterdiscordctl#65]
betterdiscordctl install
WARN: Config directory not found for Discord  (/usr/share/discord, /root/.config/discord).
ERROR: Directory 'discord_desktop_core' not found in

**Comment by LelloTech** [comment]
Can you help me?
Distro: Ubuntu 19.10/GNOME

**Comment by ObserverOfTime** [comment]
**Do not run `betterdiscordctl` with `sudo`.**

**Comment by Strxangxl** [comment]
Please help, I am kinda new to ubuntu, my version of ubuntu is 20.04

**Comment by miguel-siqueira-reis** [comment]
i have the same problem, please help me! i love betterdiscord.

![image](https://user-images.githubusercontent.com/70923414/135742420-7d7300ad-0fb7-46ae-b840-08ecd2545d1a.png)

**Comment by Prince-Noctis-XV** [comment]
I'm having the same problem, I like how observer just responds with "do not install with sudo" and quickly closed the issue.

**Comment by LimeyDot** [comment]
Install betterdiscord using .appimage from official website( https://betterdiscord.app/ )

**Comment by bb010g** [comment]
@miguel-siqueira-reis Please open a new issue. This issue is about accidentally running betterdiscordctl with sudo; your problem is Discord not being discovered in an expected use case.

> I'm having the same problem, I like how observer just responds with "do not install with sudo" and quickly closed the issue.

@Prince-Noctis-XV Open a new issue with your shell output. The visible problem in the original post was that betterdiscordctl was searching in `/root/.config/discord`, meaning they either set `XDG_CONFIG_HOME=/root/.config/discord`, set `HOME=/root`, or were running betterdiscordctl as a user with a `$HOME` of `/root`. The case is almost always that betterdiscordctl is actually being ran as `root`, which is a problem if you don't want to work on `root`'s Discord install, which is also almost always the case because it's almost always a bad idea to run Discord as `root`. To run betterdiscordctl as `root`, the original poster could have logged their seat in directly as `root`, could have used a command like `su` or `sudo -s` to open up a shell as `root` from another user's account and then run betterdiscordctl, or they could have ran it through sudo like `sudo betterdiscordctl install`. It's almost always the latter case.

We normally don't get issues like this from users who do intend to run betterdiscordctl as root because it's an advanced use case and they normally are more equipped to diagnose & solve issues outside of betterdiscordctl themselves, and when they do encounter issues in betterdiscordctl while running as `root`, they either reproduce them as a normal user if possible (to make our fixing of the issue easier) or they bring up how they're running betterdiscordctl as `root` and either why it's not relevant to the problem or why it's causing part of the problem & how their use case for running betterdiscordctl as root is valid.

If anyone opens an issue where betterdiscordctl is running as root with an explanation of why they're intentionally running betterdiscordctl as root, we'll be happy to take a look. This includes you, @Prince-Noctis-XV. Alternatively, if your problem does not involve betterdiscordctl running as `root`, which I suspect it doesn't and the log here just looks similar (besides the `/root/` part), then it should be opened as a new issue because it's a different problem than the one here, and we do want to try to solve it.

**Comment by Resxt** [comment]
I had the same issue (not running as sudo) and my issue was that I had Discord installed using Flatpak (from my OS shop)
So using the proper install command worked fine `betterdiscordctl --d-install flatpak install`

**Comment by cyberiia** [comment]
You must install Discord from the website, not from your system's software store. For some reason some files are missing.

**Comment by cyberiia** [comment]
You must install Discord from the website, not from your system's software store. For some reason some configuration files are missing, making betterdiscord impossible to work.

**Comment by cyberiia** [comment]
You must install Discord from the website, not from your system's software store. For some reason, some configuration files are missing, making betterdiscord impossible to work.

If you are running any system debian-based, open the terminal and type:

```
$ wget https://dl.discordapp.net/apps/linux/0.0.18/discord-0.0.18.deb
$ sudo apt install ./discord-0.0.18.deb

$ curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl
$ chmod +x betterdiscordctl
$ sudo mv betterdiscordctl /usr/local/bin
$ betterdiscordctl install
```

**Comment by cyberiia** [comment]
You must install Discord from the website, not from your system's software store. For some reason, some configuration files are missing, making betterdiscord impossible to work.

If you are running any system debian-based, open the terminal and type:

```
$ wget https://dl.discordapp.net/apps/linux/0.0.18/discord-0.0.18.deb
$ sudo apt install ./discord-0.0.18.deb

$ curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl
$ chmod +x betterdiscordctl
$ sudo mv betterdiscordctl /usr/local/bin
$ betterdiscordctl install
```
So you need to restart discord for it to work
`$ pkill -9 Discord`
